### PR TITLE
 Add favicon to site #44 

### PR DESCRIPTION
**Pull request by Yogeshp0012**
Attached Screenshots for the reference.

homepage
sponsor-us

### CODE REVIEW

**Comment by egiurleo** [comment]
@Yogeshp0012 This looks awesome! Would you mind merging main and pushing up your branch again? CI was broken and I made some changes to fix it.

**Comment by Yogeshp0012** [comment]
> @Yogeshp0012 This looks awesome! Would you mind merging main and pushing up your branch again? CI was broken and I made some changes to fix it.

Sure!!

**Comment by Yogeshp0012** [comment]
> @Yogeshp0012 This looks awesome! Would you mind merging main and pushing up your branch again? CI was broken and I made some changes to fix it.

Its Done...

**Review by egiurleo — APPROVED** [review]
This looks great! Thank you for the change!

**Comment by Yogeshp0012** [comment]
> This looks great! Thank you for the change!

Your Welcome

**Pull request merged**
