### PR TITLE
Adds Multiple Podcast Functionality

### PR DESCRIPTION
**Pull request by sawiggins**
As described in #73, this PR extends the podcast block to accommodate multiple podcast links. Specifically, it handles the addition the Remote Ruby podcast; however, using `map` should allow for us to continue to add podcast episodes going forward. There are currently no guardrails for rendering, so we should consider the look and amount of information going forward when adding new podcast episodes here. 

### Screenshots of Change
Large Screen
wnbrb-podcast_large
Small Screen
wnbrn-podcast_small

### CODE REVIEW

**Comment by sawiggins** [comment]
Rubocop is failing; however, my changes are only frontend changes. It doesn't seem like that fix should be part of this PR. Please advise.

**Comment by egiurleo** [comment]
@sawiggins Definitely not related to your changes! I'll make a PR tomorrow to fix. Whoever reviews this, feel free to ignore the Rubocop violations.

**Comment by egiurleo** [comment]
@sawiggins I pushed a fix to main! Feel free to merge main and push up those changes, and the issue should be fixed :)

**Review by egiurleo — APPROVED** [review]
✨ Thanks so much for working on this!

**Pull request merged**
