### PR TITLE
Sponsor page

### PR DESCRIPTION
**Pull request by RReiso**
This is a pull request for the Sponsor Us page.
We also created a reusable PageTitle component that could be used across all pages. (We modified also Home page to add the newly created PageTitle component).
We modified some styles to make the PageTitle responsive and fit into smaller and larger screens. (See photos).
Screenshot from 2021-10-27 14-50-27
Screenshot from 2021-10-27 17-44-38
Happy to change/improve whatever is necessary. :)

### CODE REVIEW

**Review by egiurleo — COMMENTED** [review]
This looks _awesome_. Super well done! One thing before I approve - can you delete the empty `app/javascript/Title.jsx` file? I assume that got added at some point and then never deleted later.

**Comment by RReiso** [comment]
Hi Emily, I have deleted the empty Title.jsx file, sorry for that, I missed it.

**Review by egiurleo — APPROVED** [review]
@RReiso nothing to be sorry for. This is excellent. Well done!

**Comment by RReiso** [comment]
Thank you @egiurleo, it was a great learning experience. And huge thanks to @Charliefea for mentoring and supporting me.

**Pull request merged**
