### PR TITLE
Fix: past meetups page grey bar alignment issue

### PR DESCRIPTION
**Pull request by RabeaGleissner**
Fixes: https://github.com/wnbrb/wnb-rb-site/issues/130

It seems that the bar was misaligned because some months have longer words than others. Increasing the width of the little month box fixed it!

To be able to test this locally I added another meetup event to the seeds. I created it for September because that's the month with the most characters.

Before and after shots 💅 

**Before: grey bar is broken up**
image

**After: all in one line!**
image

### CODE REVIEW

**Comment by lhmzhou** [comment]
Maybe it's just my decrepit eyesight, but the before and after shots look exactly the same? What do you mean by the gray box is broken up? It seems to a solid box...?

**Comment by RabeaGleissner** [comment]
@lhmzhou I had a similar thought when I first looked at [the issue](https://github.com/wnbrb/wnb-rb-site/issues/130) 😂  like - "seems fine to me, what's the problem"? It was hard to spot at first!

It's about the vertical bar that connects the months, you know that really fine grey line? That is currently not connected... and I changed it so it's a continuous grey line 😅

**Comment by lhmzhou** [comment]
Ah, I see it now! Thank you and thanks for the sharp eye for attention!

**Review by lhmzhou — APPROVED** [review]
LGTM 🎉

**Comment by RabeaGleissner** [comment]
Thanks @lhmzhou ! Could you also press some buttons so the workflow runs? 😄 
I see this message:
image

**Comment by egiurleo** [comment]
@RabeaGleissner I pressed the button! I thought I gave other people permission to do this but GitHub is not cooperating with me. I'll look more into it this weekend. Thanks for your contribution ❤️

**Comment by RabeaGleissner** [comment]
Thank you very much @egiurleo ! 💜 

Now I just need someone to approve the PR 😊

**Review by lhmzhou — APPROVED** [review]

**Comment by lhmzhou** [comment]
@egiurleo, I wonder if there are branch protection rules. Try checking out [customary repo roles](https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-peoples-access-to-your-organization-with-roles/managing-custom-repository-roles-for-an-organization).

**Comment by egiurleo** [comment]
@lhmzhou Thanks! I will take a look. I think I may also need to update your permissions to make GitHub recognize your approvals as valid.

**Pull request merged**
